using System;
using UnityEngine;

public enum FinanceMovementType
{
    Income = 0,
    Expense = 1
}

public enum FinancePaymentStatus
{
    None = 0,
    Open = 1,
    Paid = 2
}

public enum FinanceMovementOrigin
{
    Service = 0,
    ProductPurchase = 1,
    Rent = 2,
    Electricity = 3,
    Water = 4,
    Salary = 5,
    Maintenance = 6,
    Supply = 7,
    Tax = 8,
    Other = 9
}

public enum MonthlyDebtCalculationMode
{
    Fixed = 0,
    FixedPlusWorkedHours = 1
}

[Serializable]
public class FinanceMovementData
{
    [Header("Identificação")]
    public string id;
    public FinanceMovementType movementType;
    public FinanceMovementOrigin origin;

    [Header("Informações básicas")]
    public string title;
    [TextArea] public string description;

    [Header("Valores")]
    public int amount;

    [Header("Datas")]
    public long createdAtTicks;
    public long dueDateTicks;

    [Header("Pagamento")]
    public FinancePaymentStatus paymentStatus;

    [Header("Relacionamentos")]
    public string relatedRequestId;
    public string relatedClientName;

    [Header("Automação mensal")]
    public bool isAutoGenerated;
    public string recurringSourceId;
    public int referenceYear;
    public int referenceMonth;

    [Header("Base de cálculo")]
    public int usageSourceYear;
    public int usageSourceMonth;
    public int usageWorkedMinutes;

    public DateTime CreatedAt
    {
        get => new DateTime(createdAtTicks);
        set => createdAtTicks = value.Ticks;
    }

    public DateTime DueDate
    {
        get
        {
            if (dueDateTicks <= 0)
                return DateTime.MinValue;

            return new DateTime(dueDateTicks);
        }
        set => dueDateTicks = value.Ticks;
    }

    public bool HasDueDate => dueDateTicks > 0;
    public bool IsIncome => movementType == FinanceMovementType.Income;
    public bool IsExpense => movementType == FinanceMovementType.Expense;
    public bool IsPaid => paymentStatus == FinancePaymentStatus.Paid;
    public bool IsOpenExpense => IsExpense && paymentStatus == FinancePaymentStatus.Open;

    public bool IsOverdue(DateTime now)
    {
        if (!IsOpenExpense || !HasDueDate)
            return false;

        return DueDate.Date < now.Date;
    }

    public bool IsFutureExpense(DateTime now)
    {
        if (!IsOpenExpense || !HasDueDate)
            return false;

        return DueDate.Year > now.Year || (DueDate.Year == now.Year && DueDate.Month > now.Month);
    }

    public bool IsPayable(DateTime now)
    {
        if (!IsOpenExpense || !HasDueDate)
            return false;

        if (IsOverdue(now))
            return true;

        return DueDate.Year == now.Year && DueDate.Month == now.Month;
    }
}

[Serializable]
public class FinanceMovementSaveWrapper
{
    public FinanceMovementData[] items;
}

[Serializable]
public class MonthlyDebtDefinition
{
    [Header("Identificação")]
    public string recurringId = "";
    public bool enabled = true;

    [Header("Informações")]
    public string title = "Nova conta";
    [TextArea] public string description;
    public FinanceMovementOrigin origin = FinanceMovementOrigin.Other;

    [Header("Vencimento")]
    [Range(1, 28)] public int dueDay = 10;

    [Header("Cálculo")]
    public MonthlyDebtCalculationMode calculationMode = MonthlyDebtCalculationMode.Fixed;
    [Min(0)] public int baseAmount = 100;
    [Min(0f)] public float pricePerWorkedHour = 0f;
    public bool usePreviousMonthWorkedHours = true;

    [Header("Reajuste anual")]
    [Min(0f)] public float annualIncreasePercent = 0f;
    public int baseYear = 2026;
    [Range(1, 12)] public int baseMonth = 1;

    public void EnsureId()
    {
        if (string.IsNullOrWhiteSpace(recurringId))
            recurringId = Guid.NewGuid().ToString("N");
    }

    public int CalculateAmount(int referenceYear, int referenceMonth, int workedMinutes)
    {
        EnsureId();

        int adjustedBaseAmount = CalculateAdjustedBaseAmount(referenceYear, referenceMonth);

        switch (calculationMode)
        {
            case MonthlyDebtCalculationMode.Fixed:
                return Mathf.Max(0, adjustedBaseAmount);

            case MonthlyDebtCalculationMode.FixedPlusWorkedHours:
                return CalculateFixedPlusWorkedHours(adjustedBaseAmount, workedMinutes);

            default:
                return Mathf.Max(0, adjustedBaseAmount);
        }
    }

    private int CalculateAdjustedBaseAmount(int referenceYear, int referenceMonth)
    {
        int completedYears = referenceYear - baseYear;

        if (referenceMonth < baseMonth)
            completedYears--;

        completedYears = Mathf.Max(0, completedYears);

        float multiplier = Mathf.Pow(1f + (annualIncreasePercent / 100f), completedYears);
        return Mathf.Max(0, Mathf.RoundToInt(baseAmount * multiplier));
    }

    private int CalculateFixedPlusWorkedHours(int adjustedBaseAmount, int workedMinutes)
    {
        float workedHours = workedMinutes / 60f;
        int workedHoursValue = Mathf.RoundToInt(workedHours * pricePerWorkedHour);

        return Mathf.Max(0, adjustedBaseAmount + workedHoursValue);
    }
}